version: "3.8"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    healthcheck:
        test: curl -s http://es:9200 > /dev/null || exit 1
        interval: 5s
        timeout: 5s
        retries: 10
  web:
    build: .
    command: python3 app.py
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./flask-app:/opt/flask-app
volumes:
    esdata1:
      driver: local
